### PR TITLE
Support long-unicode fpaths, don't corrupt if interrupted, add `--overwrite`, `--progress` etc, backup existing files, improve logging and docs

### PR DESCRIPTION
**Pull request by ankostis**
Enhance `teslacrack.py` to make it user-friendly, suitable for unlocking (unattended) 1000s of files, without _i18n_ issues, and providing activity-report at the end.
- teslacrack:py: 
  - Support unicode long paths with `\\?\` win-prefix, accept multiple paths/files from cmd-line.
  - Do not create corrupted or empty decrypted-file when decryption fail.
  - Check expected-size and overwrite corrupted files (NEEDED when interrupted).
  - Support multiple tesla-extensions (e.g., add '.ccc').
  - Use _argparse_ lib, substitute `global` instances with objects.
  - Simplify traversing recursion with `os.walk`.
  - Add `--delete-old`, `--overwrite` & `--fix` options for dealing with existing locked or unlocked files.
  - Improve logging and ex-reporting (use -v for viewing visited files).
  - Provide stats of what has been done, and print them every N secs with `--progress`.
  - TESTED also WinPython-2.7 & 3.4, Linux Python2 & 3
- README: 
  - Improve instructions & formatting, state alternative Python version.
  - Give crack-overview and properly explain and name keys in the docs.
    - encrypted-AES-session-key, instead of "public", 
    - decrypted (or reconstructed) AES session-key, instead of "private".
    - Clarify decrypted AES-key from locked/unlocked user-files.
  - Add project-coords at the top, make badges work on Github.
  - Separate sections, add table-of-contents.
  - Convert docs from `.md --> .rst`.

### CODE REVIEW

**Comment by ankostis** [comment]
Please check [this README](/ankostis/TeslaCrack), you might like it!

And thanks for all the fish!

**Comment by ankostis** [comment]
More commits:
- ~~Don't slurp files.~~
- Add `--delete-old` and `--overwrite` options.
- Accept multiple paths and files.

**Comment by ankostis** [comment]
- CANCEL UNSLURP; it is faster and more safe to "slurp" files while decrypting.
- Do not create corrupted or empty decrypted-file when decryption fail.
- Check expected-size and overwrite corrupted files (NEEDED when interrupted).
- Provide percent-progress with ~~`--precount`~~`--progress` option.

**Comment by JonnyTech** [comment]
Nice!

**Comment by willyset** [comment]
Excuse me, my name is Willy, I want to ask my fitting contact with
ransomware .CCC, I boot my computer safe and virus scan I use Malwarebytes
and SpyHunter then fitting already completed my return to normal, then why
file could partially lost my own?

2016-01-23 20:17 GMT-08:00 JonnyTech notifications@github.com:

**Comment by Demonslay335** [comment]
@willyset Please don't post the same thing in every issue, it only clutters the comments (and this is for a pull request). I will help you in the other issue that I responded to you. I simply need a sample file to assist you.

**Comment by ankostis** [comment]
@Googulator Since you started reviewing it, I have one more things, 
apart from your feedback:

Properly encapsulate Options and Stats in 2 object-instances that are passed around the functions.
With these 2 changes, `global` is not needed, and this will alleviate some burden from the maintenance of the code.

**Pull request merged**
